### ISSUE TITLE
Issues after 16200 steps

### ISSUE THREAD

**Issue by AdamMiltonBarker** [suriyadeepan/easy_seq2seq#23]
Not sure if it hardware related or not, previously trained on CPU but now trained on a GTX 750 TI, gets to 16200 steps then Ubuntu raises error, after the initial happening of this, I deleted all data and checkpoints and started again twice but still persists, error log of event is as follows, everytime at 16200 steps:

`global step 16200 learning rate 0.5000 step-time 0.83 perplexity 16.33
^CTraceback (most recent call last):
  File "execute.py", line 319, in <module>
    train()
  File "execute.py", line 187, in train
    model.saver.save(sess, checkpoint_path, global_step=model.global_step)
  File "/home/tinn/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1335, in save
    self.export_meta_graph(meta_graph_filename)
  File "/home/tinn/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1368, in export_meta_graph
    clear_devices=clear_devices)
  File "/home/tinn/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1590, in export_meta_graph
    **kwargs)
  File "/home/tinn/.local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 651, in export_scoped_meta_graph
    as_text=as_text)
  File "/home/tinn/.local/lib/python2.7/site-packages/tensorflow/python/training/training_util.py", line 148, in write_graph
    file_io.atomic_write_string_to_file(path, graph_def.SerializeToString())
  File "/home/tinn/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1060, in SerializeToString
    return self.SerializePartialToString()
  File "/home/tinn/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1069, in SerializePartialToString
    self._InternalSerialize(out.write)
  File "/home/tinn/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1075, in InternalSerialize
    field_descriptor._encoder(write_bytes, field_value)
  File "/home/tinn/.local/lib/python2.7/site-packages/google/protobuf/internal/encoder.py", line 762, in EncodeField
    local_EncodeVarint(write, value.ByteSize())
  File "/home/tinn/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1037, in ByteSize
    size += field_descriptor._sizer(field_value)
  File "/home/tinn/.local/lib/python2.7/site-packages/google/protobuf/internal/encoder.py", line 302, in RepeatedFieldSize
    l = element.ByteSize()
  File "/home/tinn/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1037, in ByteSize
    size += field_descriptor._sizer(field_value)
  File "/home/tinn/.local/lib/python2.7/site-packages/google/protobuf/internal/encoder.py", line 247, in FieldSize
    l = local_len(value.encode('utf-8'))
`

After this training cannot continue and the UI will no longer boot up.

**Comment by AdamMiltonBarker** [comment]
Hi @suriyadeepan just wondered if you had come across this or any suggestions. Thanks in advance.

**Comment by AdamMiltonBarker** [comment]
Any feedback ?
