### ISSUE TITLE
Running execute.py

### ISSUE THREAD

**Issue by dupsy** [suriyadeepan/easy_seq2seq#26]
Got this error when running execute.py

Traceback (most recent call last):
  File "execute.py", line 300, in <module>
    train()
  File "execute.py", line 123, in train
    model = create_model(sess, False)
  File "execute.py", line 95, in create_model
    model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)
  File "/home/ubuntu/abbey_modupe/easy_seq2seq-master/seq2seq_model.py", line 166, in __init__
    self.saver = tf.train.Saver(tf.global_variables())
AttributeError: 'module' object has no attribute 'global_variables'

Did anyone witness this?

**Comment by JudeLee19** [comment]
Maybe u r using old version of tensorflow. U should try that line with tf.initialize_all_variables
