### ISSUE TITLE
TypeError in execute.py

### ISSUE THREAD

**Issue by qvex** [suriyadeepan/easy_seq2seq#35]
Preparing data in working_dir/
Creating 3 layers of 256 units.
Traceback (most recent call last):
  File "execute.py", line 300, in <module>
    train()
  File "execute.py", line 123, in train
    model = create_model(sess, False)
  File "execute.py", line 95, in create_model
    model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)
  File "/home/localhost/test_case_1/seq2seq_model.py", line 167, in __init__
    self.saver = tf.train.Saver(tf.initialize_all_variables())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 986, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1015, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 602, in build
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 498, in _ValidateAndSliceInputs
    names_to_saveables = BaseSaverBuilder.OpListToDict(names_to_saveables)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 453, in OpListToDict
    "list: %s" % op_list)
TypeError: Variables to save should be passed in a dict or a list: name: "init"
op: "NoOp"
input: "^init/NoOp"
input: "^init/NoOp_1"

**Comment by PraveenKumarCSE** [comment]
same issue...!

**Comment by Mohanmk1** [comment]
hi 
facing below issues , could you please help me to resolve it

![image](https://cloud.githubusercontent.com/assets/28388659/26023801/028d804c-37e2-11e7-9e97-9f435dabb0cb.png)

**Comment by syw2014** [comment]
same issue, details as bellow:
Creating 3 layers of 256 units.
Traceback (most recent call last):
  File "D:/github/easy_seq2seq/easy_seq2seq/execute.py", line 310, in <module>
    train()
  File "D:/github/easy_seq2seq/easy_seq2seq/execute.py", line 133, in train
    model = create_model(sess, False)
  File "D:/github/easy_seq2seq/easy_seq2seq/execute.py", line 104, in create_model
    forward_only=forward_only
  File "D:\github\easy_seq2seq\easy_seq2seq\seq2seq_model.py", line 163, in __init__
    softmax_loss_function=softmax_loss_function)
  File "D:\install\Anaconda3.4.2\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 1221, in model_with_buckets
    softmax_loss_function=softmax_loss_function))
  File "D:\install\Anaconda3.4.2\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 1134, in sequence_loss
    softmax_loss_function=softmax_loss_function))
  File "D:\install\Anaconda3.4.2\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 1089, in sequence_loss_by_example
    crossent = softmax_loss_function(labels=target, logits=logit)
TypeError: sampled_loss() got an unexpected keyword argument 'logits'

**Comment by ManivannanMurugavel** [comment]
find sampled_loss def from seq2seq_model.py and change the lines
def sampled_loss(labels, logits):
        labels = tf.reshape(labels, [-1, 1])
        return tf.nn.sampled_softmax_loss(tf.transpose(w), b, labels, logits, 
                                          config.NUM_SAMPLES, config.DEC_VOCAB)
