### ISSUE TITLE
how to run python3 execute.py successful for tf1.4?

### ISSUE THREAD

**Issue by orange-jacky** [suriyadeepan/easy_seq2seq#44]
hi,
    i install tf1.4 on my mac, run easy_seq2seq demo, and it failed.
    anyone  can help me make it run fine, thanks.
 

macbookpro:easy_seq2seq fredlee$ python3 execute.py 
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "execute.py", line 31, in <module>
    import seq2seq_model
  File "/Users/fredlee/Downloads/tensorflow/study/easy_seq2seq/seq2seq_model.py", line 28, in <module>
    from tensorflow.models.rnn.translate import data_utils
ModuleNotFoundError: No module named 'tensorflow.models'

**Comment by JohnnyLai92** [comment]
i install tf1.4,tf1.0,tf0.12,tf0.9 on ubuntu, only tf0.9 can run, on tf1.4 has same issue~
